version: "3"
services:
  node:
    container_name: parcel-catalog
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/parcel-catalog
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    networks:
      - mongo-compose-network
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongo-compose-network

networks: 
  mongo-compose-network:
    driver: bridge